scrapdeal/account/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from django.shortcuts import render

from . import views
from . import forms

app_name = 'account'

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(
             form_class=forms.UserLoginForm,
             template_name='registration/login.html',
         ),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(
             template_name='registration/logged_out.html'

         ),
         name='logout'),



    # Сброс пароля
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             form_class=forms.UserPasswordResetForm,
             template_name='registration/password_reset_form.html',
             email_template_name='registration/password_reset_email.html',
             success_url=reverse_lazy('storage:password_reset_done'),
             from_email=settings.EMAIL_HOST_USER,
         ),
         name='password_reset'),

    # Сброс пароля: После отправки письма
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_done.html'
         ),
         name='password_reset_done'),

    # Сброс пароля: Ссылка в письме
    path('password_reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html',
             success_url=reverse_lazy('storage:password_reset_complete'),
         ),
         name='password_reset_confirm'),

    # Сброс пароля: ввод ногового пароля
    path('password_reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_complete.html'
         ),
         name='password_reset_complete'),

    # path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    # path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

scrapdeal/scrap/urls.py
from django.urls import path, include
from .views import account_notifications, account, get_my_orders, get_orders, get_order, create_order

app_name = 'scrap'

urlpatterns = [
    path('', account, name='account'),
    path('notifications', account_notifications, name='account-notifications'),
    path('my-orders', get_my_orders, name='my-orders'),
    path('orders', get_orders, name="orders"),
    path("order/<slug:slug>", get_order, name="order-detail"),
    path('create-order', create_order, name="create-order"),
]

scrapdeal/scrapdeal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scrap.urls', namespace='scrap'),),
    path('^tinymce/', include('tinymce.urls')),
    path('account/', include('account.urls', namespace='account'),),
]

# media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

scrapdeal/scrap/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth import get_user_model
from tinymce.models import HTMLField


UserModel = get_user_model()

class CategoryMaterial(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название категории')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория материала'
        verbose_name_plural = 'Категории материалов'


class Customer(models.Model):
    user = models.OneToOneField(UserModel, on_delete=models.CASCADE, verbose_name='Пользователь', related_name='customer')

    def __str__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name = 'Заказчик'
        verbose_name_plural = 'Заказчики'


class Executor(models.Model):
    user = models.OneToOneField(UserModel, on_delete=models.CASCADE, verbose_name='Пользователь', related_name='executor')
    executmaterials = models.ManyToManyField(CategoryMaterial, blank=True,
                                             verbose_name='Категории материала',
                                             related_name='executors')

    def __str__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name = 'Исполнитель'
        verbose_name_plural = 'Исполнители'


class Factory(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название завода')
    slug = models.SlugField(max_length=100, unique=True, db_index=True, verbose_name='Ссылка')
    customers = models.ManyToManyField(Customer,
                                       blank=True,
                                       verbose_name='Исполнители',
                                       related_name='factories')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Завод'
        verbose_name_plural = 'Заводы'


class Order(models.Model):
    STATUS = (
        ('1_new', 'Новый'),
        ('2_progress', 'В процессе'),
        ('3_completed', 'Завершен'),
        ('4_canceled', 'Отменен'),
    )
    title = models.CharField(max_length=100, verbose_name='Название заказа')
    slug = models.SlugField(max_length=100, unique=True, db_index=True, verbose_name='Ссылка')
    description = HTMLField(blank=True, verbose_name='Описание')
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='customer_orders',
                                 verbose_name='Заказчик',)
    executor = models.ForeignKey(Executor, null=True, blank=True, related_name='executed_orders',
                                 on_delete=models.SET_NULL, verbose_name='Исполнитель')
    factory = models.ForeignKey(Factory, on_delete=models.CASCADE, related_name='factory_orders',
                                verbose_name='Завод')
    material_name = models.CharField(max_length=100, verbose_name='Название материала')
    material_category = models.ForeignKey(CategoryMaterial, on_delete=models.CASCADE,
                                          verbose_name='Категория материала')
    status = models.CharField(max_length=15, choices=STATUS, default='1_new', verbose_name='Статус')
    date_start = models.DateField(verbose_name='Дата начала', blank=True,)
    date_end = models.DateField(verbose_name='Дата окончания', blank=True,
                                default=(timezone.now() + timezone.timedelta(days=5)))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлен')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        ordering = ('-date_end','status', '-created_at', '-updated_at', )



class Comment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ', related_name='comments')
    content = HTMLField(blank=True, verbose_name='Комментарий')
    author = models.ForeignKey(UserModel, on_delete=models.SET_NULL, related_name='comments',
                               null=True, verbose_name='Автор')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлен')

    def __str__(self):
        return self.author.get_full_name() + ' - ' + self.order.title

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('-created_at',)

scrapdeal/account/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import PasswordResetForm
from django.utils.translation import gettext_lazy
from django.contrib.auth import authenticate, get_user_model, password_validation
from django.core.exceptions import ValidationError

from .models import Profile

UserModel = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField(
        required=True,
        label=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control mb-3',
            'placeholder': 'Логин',
            'name': 'username'
        })
    )
    password = forms.CharField(
        required=True,
        label=False,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control mb-3',
            'placeholder': 'Пароль',
            'name': 'password'
        })
    )

    error_messages = {
        "invalid_login": gettext_lazy(
            "Пожалуйста, введите правильный  %(username)s и пароль. Обратите внимание, что оба"
            "поля могут быть чувствительны к регистру."
        ),
        "inactive": gettext_lazy("Этот аккаунт заблокирован."),
    }

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)
        self.username_field = UserModel._meta.get_field(UserModel.USERNAME_FIELD)
        username_max_length = self.username_field.max_length or 254
        self.fields["username"].max_length = username_max_length
        self.fields["username"].widget.attrs["maxlength"] = username_max_length

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username is not None and password:
            self.user_cache = authenticate(
                self.request, username=username, password=password
            )
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise ValidationError(
                self.error_messages["inactive"],
                code="inactive",
            )

    def get_user(self):
        return self.user_cache

    def get_invalid_login_error(self):
        return ValidationError(
            self.error_messages["invalid_login"],
            code="invalid_login",
            params={"username": "username"},
        )


class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label=False,
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control  mb-3',
                'placeholder': 'E-mail',
                'name': 'EMAIL'
            }
        )
    )

    def clean_email(self):
        email = self.cleaned_data['email']
        # Если пользователь с такой почтой не существует
        if not UserModel.objects.filter(email__iexact=email, is_active=True).exists():
            raise forms.ValidationError('Пользователь с такой почтой не существует')
        return email


class ProfileEditForm(forms.ModelForm):
    first_name = forms.CharField(
        required=True,
        label=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mb-3',
                'placeholder': 'Имя',
                'name': 'first_name'
            }
        ),
        error_messages={'required': 'Пожалуйста, введите ваше имя.'}
    )
    last_name = forms.CharField(
        required=True,
        label=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mb-3',
                'placeholder': 'Фамилия',
                'name': 'last_name'
            }
        ),
        error_messages={'required': 'Пожалуйста, введите вашу фамилию.'}
    )
    email = forms.EmailField(
        required=True,
        label=False,
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control mb-3',
                'placeholder': 'E-mail',
                'name': 'email'
            }
        ),
        error_messages={'required': 'Пожалуйста, введите вашу почту.'}
    )

    class Meta:
        model = Profile
        fields = [
            'first_name',
            'last_name',
            'email',
            'photo',
        ]
        widgets = {
            'photo': forms.FileInput(
                attrs={
                    'class': 'form-control mb-3',
                    'placeholder': 'Фото',
                    'name': 'photo'
                }
            ),
        }
        labels = {
            'photo': '',
        }

    def clean_email(self):
        data = self.cleaned_data['email']
        if UserModel.objects.filter(email=data).exists():
            raise forms.ValidationError('Пользователь с такой почтой уже существует')
        return data

scrapdeal/scrap/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from tinymce.models import HTMLField
from .models import Order, Factory


class OrderForm(forms.ModelForm):
    factory = forms.ModelChoiceField(queryset=Factory.objects.none(), widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Order
        fields = ['title', 'description', 'factory', 'material_name', 'material_category', 'date_start', 'date_end']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите название'}),
            'description': TinyMCE(attrs={'cols': 80, 'rows': 30, 'class': 'form-control'}),
            'factory': forms.Select(attrs={'class': 'form-control'}),
            'material_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите материал'}),
            'material_category': forms.Select(attrs={'class': 'form-control'}),
            'date_start': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'date_end': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')  # Получаем пользователя из аргументов
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['factory'].queryset = Factory.objects.filter(customers=user.customer)

scrapdeal/account/views.py
from django.shortcuts import render

# Create your views here.

scrapdeal/scrap/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.text import slugify

from .forms import OrderForm
from .models import Customer, Order, Executor


# Create your views here.


@login_required
def account(request):
    profile = request.user
    context = {'user': profile}
    # если user - заказчик
    if Customer.objects.filter(user=profile).exists():
        context['customer'] = Customer.objects.get(user=profile)
    return render(request, 'scrap/account.html', context)


def account_notifications(request):
    profile = request.user
    context = {'profile': profile}
    return render(request, 'account-notifications.html', context)

# только get
@login_required
def get_my_orders(request):
    # Мы хотим получить только свои заказы
    customer = request.user.customer
    orders = Order.objects.filter(customer=customer)
    context = {'orders': orders}
    return render(request, 'scrap/my-orders.html', context)


@login_required
def get_orders(request):
    # Мы хотим получить все заказы
    orders = Order.objects.all()
    context = {'orders': orders}
    return render(request, 'scrap/orders.html', context)


@login_required
def get_order(request, slug):
    order = Order.objects.get(slug=slug)
    context = {'order': order}
    return render(request, 'scrap/order-detail.html', context)


@login_required
def create_order(request):
    """Create an order"""
    if request.method == 'POST':
        form = OrderForm(request.POST, user=request.user)
        if form.is_valid():
            order = form.save(commit=False)
            # slug
            order.customer = request.user.customer
            # prepopulated_fields
            order.slug = slugify(order.title)
            order.save()
            return redirect('scrap:my-orders')
    else:
        form = OrderForm(user=request.user)
    context = {'form': form, 'categories': form.fields['material_category'].queryset}

    return render(request, 'scrap/create-order.html', context)


@login_required
def take_order(request, slug):
    order = Order.objects.get(slug=slug)
    if Executor.objects.filter(user=request.user).exists():
        order.executor = Executor.objects.get(user=request.user)
    order.save()
    return redirect('scrap:my-orders')

scrapdeal/templates/scrap/account.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Профил{% endblock %}
{% block content %}
<div class="card m-3 ">
  <h5 class="card-header">Профил</h5>
  <div class="card-body">
    <div class="d-flex align-items-start align-items-sm-center gap-4">
      <img
              src="{{ user.photo.url }}"
              alt="user-avatar"
              class="d-block rounded"
              height="100"
              width="100"
              id="uploadedAvatar"
      />

    </div>
  </div>
  <hr class="my-0"/>
  <div class="card-body">
    <form id="formAccountSettings" method="POST">
      <div class="row">
        <div class="mb-3 col-md-6">
          <label for="firstName" class="form-label">Имя пользователя</label>
          <input
                  class="form-control"
                  type="text"
                  id="firstName"
                  name="firstName"
                  value="{{ user.username }}"
                  readonly
          />
        </div>
        <div class="mb-3 col-md-6">
          <label for="lastName" class="form-label">Полное имя</label>
          <input class="form-control" type="text" name="lastName" id="lastName" value="{{ user.get_full_name }}" readonly/>
        </div>
        <div class="mb-3 col-md-6">
          <label for="email" class="form-label">E-mail</label>
          <input
                  class="form-control"
                  type="text"
                  id="email"
                  name="email"
                  value="{{ user.email }}"
                  readonly
          />
        </div>
        <div class="mb-3 col-md-6">
          <label for="organization" class="form-label">Заводы</label>
          <input
                  type="text"
                  class="form-control"
                  id="organization"
                  name="organization"
                  value="{% for factory in customer.factories.all %}{{ factory.title }}{% if not forloop.last %}, {% endif %}{% endfor %}"
                  readonly
          />
        </div>
      </div>
    </form>
  </div>
  <a href="{% url 'account:logout' %}" class="btn btn-danger ">Выход</a>
</div>
{% endblock %}

scrapdeal/templates/scrap/create-order.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Создать заявку{% endblock %}
{% block content %}
<div class="container mt-5">
    <h2>Создать заявку</h2>
    <form method="post" action="{% url 'scrap:create-order' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Название</label>
            <input type="text" name="title" maxlength="100" class="form-control" id="id_title" required>
        </div>
        <div class="form-group">
            <label for="id_description">Описание</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label for="id_factory">Фабрика</label>
            {{ form.factory }}
        </div>
        <div class="form-group">
            <label for="id_material_name">Материал</label>
            <input type="text" name="material_name" class="form-control" id="id_material_name" required>
        </div>
       <!-- Choice is Foreign Key from MaterialCategory -->
        <div class="form-group">
            <label for="id_material_category">Категория</label>
            {{ form.material_category }}
        </select>
        </div>
        <div class="form-group">
            <label for="id_date_start">Дата начала</label>
            <input type="date" name="date_start" class="form-control" id="id_date_start" required>
        </div>
        <div class="form-group">
            <label for="id_date_end">Дата окончания</label>
            <input type="date" name="date_end" class="form-control" id="id_date_end" required>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Отправить заявку</button>
    </form>
</div>
{% endblock %}

scrapdeal/templates/scrap/dashboard.html
{% extends "scrap/base.html" %}
{% load scrap_tags %}
{% block title %}Протокола{% endblock %}

{% block content %}
<div class="row mt-1 mb-1 pt-1 pb-1">
    <div class="col-6 d-grid">
        <ul class="list-group list-group-flush"  style="text-align: left; border-radius: 5px">
            <li class="list-group-item">Ф.И.О.: {{ employ}}</li>
            <li class="list-group-item">Логин: {{ employ.user.username }} </li>
            <li class="list-group-item">Почта: {{ employ.user.email }} </li>
            <li class="list-group-item">Цех: {{ employ.workshop.number }} </li>
            <li class="list-group-item">Название цеха: {{ employ.workshop.name }}</li>
            <li class="list-group-item">Начальник цеха: {{ employ.workshop.head }}</li>
        </ul>
    </div>

    <div class="col-6 d-grid">
        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">Номер заявки: {{ order.number }} </div>
                      Создал {{ order.created_by }} {{ order.created_at }}
                      Ответсвенный: {{ order.responsible }}
                </div>

            </li>

        </ul>
    </div>

</div>
{% endblock %}

scrapdeal/templates/scrap/my-orders.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Профил{% endblock %}
{% block content %}

<div class="card m-1">
  <!-- Должна находиться в верхней части страницы в правом углу только кнопка "создать заявку" -->
  <div class="container-fluid">
    <div class="row justify-content-end mt-3">
      <div class="col-auto">
        <a href="{% url 'scrap:create-order' %}" class="btn btn-primary">Создать заявку</a>
      </div>
    </div>
  </div>
  <h5 class="card-header">Заявки</h5>
  <div class="table-responsive text-nowrap">
    <table class="table">
      <thead>
      <tr>
        <th>Название</th>
        <th>Завод</th>
        <th>Исполнитель</th>
        <th>Статус</th>
        <th>Действие</th>
      </tr>
      </thead>
      <tbody class="table-border-bottom-0">
      {% for order in orders %}

      <tr>
        <td><i class="fab fa-angular fa-lg text-danger me-3"></i>
          <a href="{% url 'scrap:order-detail' order.slug %}"><strong>{{ order.title }}</strong> </a>
        </td>
        <td>{{ order.factory }}</td>
        <td>{{ order.executor}}</td>
        <td>
          {% include 'component/order/status.html' with order=order %}
        </td>
        <td>
          <div class="dropdown">
            <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
              <i class="bx bx-dots-vertical-rounded"></i>
            </button>
          </div>
        </td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

scrapdeal/templates/scrap/order-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Профил{% endblock %}
{% block content %}

<div class="row my-5 mx-2">
<div class="col-xl">
  <div class="card mb-4">
    <div class="card-header d-flex justify-content-between align-items-center">
      <h5 class="mb-0">Заявка {{ order.title }}</h5> <div class="float-end">{% include 'component/order/status.html' with order=order %}</div>
<!--      <<small class="text-muted float-end">Default label</small>-->
    </div>
    <div class="card-body">
        <div class="mb-3">
          <label class="form-label" for="basic-default-fullname">Заказчик</label>
          <input type="text" class="form-control" id="basic-default-fullname" value="{{ order.customer }}" readonly>
        </div>
        <div class="mb-3">
          <label class="form-label" for="basic-default-company">Ответственное лицо</label>
          <input type="text" class="form-control" id="basic-default-company" value="{{ order.executor }}" readonly>
        </div>
        <div class="mb-3">
          <label class="form-label" for="basic-default-phone">Завод</label>
          <input type="text" id="basic-default-phone" class="form-control" value="{{ order.factory }}"  readonly>
        </div>
        <div class="mb-3">
          <label class="form-label" for="basic-default-message">Описание</label>
          <div>{{ order.description|safe }}</div>

<!--          <textarea id="basic-default-message" class="form-control" readonly">{{ order.description }} </textarea>-->

        </div>
    {% if request.user.executor %}
    {% include 'component/order/button_panel.html' with order=order %}
    {% endif %}
    </div>
  </div>
</div>
</div>

{% endblock %}

scrapdeal/templates/scrap/orders.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Профил{% endblock %}
{% block content %}
<div class="card">
  <h5 class="card-header">Заявки</h5>
  <div class="table-responsive text-nowrap">
    <table class="table">
      <thead>
      <tr>
        <th>Название</th>
        <th>Завод</th>
        <th>Заявитель</th>
        <th>Исполнитель</th>
        <th>Статус</th>
        <th>Действие</th>
      </tr>
      </thead>
      <tbody class="table-border-bottom-0">
      {% for order in orders %}

      <tr>
        <td><i class="fab fa-angular fa-lg text-danger me-3"></i>
          <a href="{% url 'scrap:order-detail' order.slug %}"><strong>{{ order.title }}</strong> </a>
        </td>
        <td>{{ order.factory }}</td>
        <td>{{ order.customer}}</td>
        <td>{{ order.executor}}</td>
        <td>
          {% include 'component/order/status.html' with order=order %}
        </td>
        <td>
          {% include 'component/order/action.html' with order=order %}
        </td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}