scrapdeal/account/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from django.shortcuts import render

from . import views
from . import forms

app_name = 'account'

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(
             form_class=forms.UserLoginForm,
             template_name='registration/login.html',
         ),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(
             template_name='registration/logged_out.html'

         ),
         name='logout'),



    # Сброс пароля
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             form_class=forms.UserPasswordResetForm,
             template_name='registration/password_reset_form.html',
             email_template_name='registration/password_reset_email.html',
             success_url=reverse_lazy('storage:password_reset_done'),
             from_email=settings.EMAIL_HOST_USER,
         ),
         name='password_reset'),

    # Сброс пароля: После отправки письма
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_done.html'
         ),
         name='password_reset_done'),

    # Сброс пароля: Ссылка в письме
    path('password_reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html',
             success_url=reverse_lazy('storage:password_reset_complete'),
         ),
         name='password_reset_confirm'),

    # Сброс пароля: ввод ногового пароля
    path('password_reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_complete.html'
         ),
         name='password_reset_complete'),

    # path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    # path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

scrapdeal/scrap/urls.py
from django.urls import path, include
from .views import account_notifications, account, get_my_orders, get_orders, get_order, create_order

app_name = 'scrap'

urlpatterns = [
    path('', account, name='account'),
    path('notifications', account_notifications, name='account-notifications'),
    path('my-orders', get_my_orders, name='my-orders'),
    path('orders', get_orders, name="orders"),
    path("order/<slug:slug>", get_order, name="order-detail"),
    path('create-order', create_order, name="create-order"),
]

scrapdeal/scrapdeal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scrap.urls', namespace='scrap'),),
    path('^tinymce/', include('tinymce.urls')),
    path('account/', include('account.urls', namespace='account'),),
]

# media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

scrapdeal/account/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.mail import send_mail
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User, PermissionsMixin, Group
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from PIL import Image
from .managers import ProfileManager


class Profile(AbstractBaseUser, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(
        max_length=100,
        verbose_name='Имя',
        blank=True,
    )
    last_name = models.CharField(
        max_length=100,
        verbose_name='Фамилия',
        blank=True,
    )
    surname = models.CharField(
        max_length=100,
        verbose_name='Отчество',
        blank=True,
    )
    email = models.EmailField(
        _("email address"),
        blank=True,
        null=True
    )
    photo = models.ImageField(
        upload_to='media/%Y/%m/%d',
        default='static/profile_default.jpg',
        blank=True,
        verbose_name='Фото'
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )

    objects = ProfileManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


    def get_full_name(self):
        """
        Возвращает фамилии, имя и отчество с пробелом между ними
        """
        full_name = "%s %s %s" % (self.last_name, self.first_name, self.surname)
        return full_name.strip()

    def get_short_name(self):
        """Возвращает Фамилию и инициалы."""
        if self.first_name and self.last_name:
            if self.surname:
                short_name = f"{self.last_name} {self.first_name[0]}. {self.surname[0]}."
            else:
                short_name = f"{self.last_name} {self.first_name[0]}."
            return short_name
        return self.first_name

    def has_group(self, group_name):
        """Возвращает True, если пользователь состоит в указанной группе."""
        if self.is_superuser:
            return True
        try:
            groups = self.groups.filter(name=group_name)
            return True
        except Group.DoesNotExist:
            return False

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Отправляет электронное письмо этому пользователю."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

scrapdeal/account/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import PasswordResetForm
from django.utils.translation import gettext_lazy
from django.contrib.auth import authenticate, get_user_model, password_validation
from django.core.exceptions import ValidationError

from .models import Profile

UserModel = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField(
        required=True,
        label=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control mb-3',
            'placeholder': 'Логин',
            'name': 'username'
        })
    )
    password = forms.CharField(
        required=True,
        label=False,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control mb-3',
            'placeholder': 'Пароль',
            'name': 'password'
        })
    )

    error_messages = {
        "invalid_login": gettext_lazy(
            "Пожалуйста, введите правильный  %(username)s и пароль. Обратите внимание, что оба"
            "поля могут быть чувствительны к регистру."
        ),
        "inactive": gettext_lazy("Этот аккаунт заблокирован."),
    }

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)
        self.username_field = UserModel._meta.get_field(UserModel.USERNAME_FIELD)
        username_max_length = self.username_field.max_length or 254
        self.fields["username"].max_length = username_max_length
        self.fields["username"].widget.attrs["maxlength"] = username_max_length

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username is not None and password:
            self.user_cache = authenticate(
                self.request, username=username, password=password
            )
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise ValidationError(
                self.error_messages["inactive"],
                code="inactive",
            )

    def get_user(self):
        return self.user_cache

    def get_invalid_login_error(self):
        return ValidationError(
            self.error_messages["invalid_login"],
            code="invalid_login",
            params={"username": "username"},
        )


class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label=False,
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control  mb-3',
                'placeholder': 'E-mail',
                'name': 'EMAIL'
            }
        )
    )

    def clean_email(self):
        email = self.cleaned_data['email']
        # Если пользователь с такой почтой не существует
        if not UserModel.objects.filter(email__iexact=email, is_active=True).exists():
            raise forms.ValidationError('Пользователь с такой почтой не существует')
        return email


class ProfileEditForm(forms.ModelForm):
    first_name = forms.CharField(
        required=True,
        label=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mb-3',
                'placeholder': 'Имя',
                'name': 'first_name'
            }
        ),
        error_messages={'required': 'Пожалуйста, введите ваше имя.'}
    )
    last_name = forms.CharField(
        required=True,
        label=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mb-3',
                'placeholder': 'Фамилия',
                'name': 'last_name'
            }
        ),
        error_messages={'required': 'Пожалуйста, введите вашу фамилию.'}
    )
    email = forms.EmailField(
        required=True,
        label=False,
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control mb-3',
                'placeholder': 'E-mail',
                'name': 'email'
            }
        ),
        error_messages={'required': 'Пожалуйста, введите вашу почту.'}
    )

    class Meta:
        model = Profile
        fields = [
            'first_name',
            'last_name',
            'email',
            'photo',
        ]
        widgets = {
            'photo': forms.FileInput(
                attrs={
                    'class': 'form-control mb-3',
                    'placeholder': 'Фото',
                    'name': 'photo'
                }
            ),
        }
        labels = {
            'photo': '',
        }

    def clean_email(self):
        data = self.cleaned_data['email']
        if UserModel.objects.filter(email=data).exists():
            raise forms.ValidationError('Пользователь с такой почтой уже существует')
        return data

scrapdeal/account/views.py
from django.shortcuts import render

# Create your views here.

scrapdeal/templates/component/account-settings/account.html
{% extends 'component/account-settings/base.html' %}
{% load static %}
{% block account_content %}

<div class="card mb-4">
  <h5 class="card-header">Профил</h5>
  <div class="card-body">
    <div class="d-flex align-items-start align-items-sm-center gap-4">
      <img
              src="{% static '/img/avatars/1.png' %}"
              alt="user-avatar"
              class="d-block rounded"
              height="100"
              width="100"
              id="uploadedAvatar"
      />

    </div>
  </div>
  <hr class="my-0"/>
  <div class="card-body">
    <form id="formAccountSettings" method="POST">
      <div class="row">
        <div class="mb-3 col-md-6">
          <label for="firstName" class="form-label">First Name</label>
          <input
                  class="form-control"
                  type="text"
                  id="firstName"
                  name="firstName"
                  value="John"
                  readonly
          />
        </div>
        <div class="mb-3 col-md-6">
          <label for="lastName" class="form-label">Last Name</label>
          <input class="form-control" type="text" name="lastName" id="lastName" value="Doe" readonly/>
        </div>
        <div class="mb-3 col-md-6">
          <label for="email" class="form-label">E-mail</label>
          <input
                  class="form-control"
                  type="text"
                  id="email"
                  name="email"
                  value="john.doe@example.com"
                  placeholder="john.doe@example.com"
                  readonly
          />
        </div>
        <div class="mb-3 col-md-6">
          <label for="organization" class="form-label">Organization</label>
          <input
                  type="text"
                  class="form-control"
                  id="organization"
                  name="organization"
                  value="ThemeSelection"
                  readonly
          />
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

scrapdeal/templates/component/account-settings/base.html
{% load static %}
<div class="container-xxl flex-grow-1 container-p-y">

  <div class="row">
    <div class="col-md-12">
      <ul class="nav nav-pills flex-column flex-md-row mb-3">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'scrap:account' %}"><i class="bx bx-user me-1"></i> Аккаунт </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'scrap:account-notifications' %}"
          ><i class="bx bx-bell me-1"></i> События </a
          >
        </li>
      </ul>
      {% block account_content %}

      {% endblock %}

    </div>
  </div>

</div>

scrapdeal/templates/component/account-settings/delete.html
<div class="card">
  <h5 class="card-header">Delete Account</h5>
  <div class="card-body">
    <div class="mb-3 col-12 mb-0">
      <div class="alert alert-warning">
        <h6 class="alert-heading fw-bold mb-1">Are you sure you want to delete your account?</h6>
        <p class="mb-0">Once you delete your account, there is no going back. Please be certain.</p>
      </div>
    </div>
    <form id="formAccountDeactivation" onsubmit="return false">
      <div class="form-check mb-3">
        <input
                class="form-check-input"
                type="checkbox"
                name="accountActivation"
                id="accountActivation"
        />
        <label class="form-check-label" for="accountActivation"
        >I confirm my account deactivation</label
        >
      </div>
      <button type="submit" class="btn btn-danger deactivate-account">Deactivate Account</button>
    </form>
  </div>
</div>

scrapdeal/templates/component/account-settings/notifications.html
{% extends 'component/account-settings/base.html' %}
{% load static %}
{% block account_content %}
<div class="card mb-4">
  <h5 class="card-header">Уведомления</h5>
</div>
{% endblock %}