scrapdeal/scrap/urls.py
from django.urls import path, include
from .views import account_notifications, account, get_my_orders, get_orders, get_order, create_order

app_name = 'scrap'

urlpatterns = [
    path('', account, name='account'),
    path('notifications', account_notifications, name='account-notifications'),
    path('my-orders', get_my_orders, name='my-orders'),
    path('orders', get_orders, name="orders"),
    path("order/<slug:slug>", get_order, name="order-detail"),
    path('create-order', create_order, name="create-order"),
]

scrapdeal/scrapdeal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scrap.urls', namespace='scrap'),),
    path('^tinymce/', include('tinymce.urls')),
    path('account/', include('account.urls', namespace='account'),),
]

# media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

scrapdeal/templates/component/footer.html
<footer class="content-footer footer bg-footer-theme">
    <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
      <div class="mb-2 mb-md-0">
        ©
        <script>
          document.write(new Date().getFullYear());
        </script>

      </div>
      <div>
        <a href="https://themeselection.com/license/" class="footer-link me-4" target="_blank">License</a>
      </div>
    </div>
  </footer>

scrapdeal/templates/component/sidebar.html
{% load static %}
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
  <div class="app-brand demo">
    <a href="{% url 'scrap:account' %}" class="app-brand-link">
      <img src="{% static 'img/scrapdeal_32.png' %}" alt="">
    </a>

    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
      <i class="bx bx-chevron-left bx-sm align-middle"></i>
    </a>
  </div>

  <div class="menu-inner-shadow"></div>

  <ul class="menu-inner py-1">
    <!-- Dashboard -->
    <li class="menu-item">
      <a href="{% url 'scrap:account' %}" class="menu-link">
        <i class="menu-icon tf-icons bx bx-home-circle"></i>
        <div data-i18n="Analytics">Личный кабинет</div>
      </a>
    </li>

    <!-- Layouts -->
    {% if user.customer %}
    <li class="menu-item">
      <a href="{% url 'scrap:my-orders' %}" class="menu-link">
        <i class="menu-icon tf-icons bx bx-dock-top"></i>
        <div data-i18n="Account Settings">Мои заявки</div>
      </a>
    </li>
    {% endif %}
    {% if user.executor %}
    <li class="menu-item">
      <a href="{% url 'scrap:orders' %}" class="menu-link">
        <i class="menu-icon tf-icons bx bx-dock-top"></i>
        <div data-i18n="Account Settings">Заявки</div>
      </a>
    </li>
    {% endif %}

  </ul>
</aside>
<!-- / Menu -->